model:
  base_learning_rate: 0.0625
  target: taming.models.hybrid_transformer.HybridTransformer
  params:
    cond_stage_key: gray
    cond_stage_config: __is_unconditional__
    first_stage_key: image
    transformer_config:
      target: taming.modules.transformer.chromagpt.GPT
      params:
        vocab_size: 2048 #  the number of codes
        block_size: 512 # full model is 768 (= 256 + 512)
        n_layer: 24
        n_head: 16
        n_embd: 256 # full model is 512
    first_stage_config:
      target: taming.models.chromavq.ChromaVQ
      params:
        ckpt_path: ./logs/2022-11-15T12-39-40_chroma_vqgan_mark/checkpoints/last.ckpt 
        embed_dim: 256
        n_embed: 2048
        encoder_config:
          double_z: false
          z_channels: 256
          resolution: 256
          in_channels: 3
          ch: 128
          ch_mult:
          - 1
          - 1
          - 2
          - 2
          - 4
          num_res_blocks: 2
          attn_resolutions:
          - 16
          dropout: 0.0
        encoder_gray_config:
          double_z: false
          z_channels: 256
          resolution: 256
          in_channels: 1
          ch: 128
          ch_mult:
          - 1
          - 1
          - 2
          - 2
          - 4
          num_res_blocks: 2
          attn_resolutions:
          - 16
          dropout: 0.0
        decoder_config:
          z_channels: 512
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 1
          - 2
          - 2
          - 4
          num_res_blocks: 2
          attn_resolutions:
          - 16
          dropout: 0.0
        lossconfig:
          target: taming.modules.losses.DummyLoss
data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 8
    num_workers: 8
    train:
      target: taming.data.chroma.ChromaTrain2
      params:
        use_arbitrary_gray: True
        training_images_list_file: datasets/train.txt
        size: 256
    validation:
      target: taming.data.chroma.ChromaTest2
      params:
        use_arbitrary_gray: True
        test_images_list_file: datasets/test.txt
        size: 256
