model:
  base_learning_rate: 4.5e-6
  target: taming.models.chromavq.ChromaVQ
  params:
    vqhint: True
    embed_dim: 256
    n_embed: 2048
    encoder_config:
      double_z: False
      z_channels: 256
      resolution: 256
      in_channels: 3
      ch: 128
      ch_mult: [ 1,1,2,2,4]
      num_res_blocks: 2
      attn_resolutions: [16]
      dropout: 0.0
    encoder_gray_config:
      double_z: False
      z_channels: 256
      resolution: 256
      in_channels: 1
      ch: 128
      ch_mult: [ 1,1,2,2,4] 
      num_res_blocks: 2
      attn_resolutions: [16]
      dropout: 0.0
    decoder_config:
      z_channels: 512
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult: [ 1,1,2,2,4]  
      num_res_blocks: 2
      attn_resolutions: [16]
      dropout: 0.0

    lossconfig:
      target: taming.modules.losses.vqperceptual.VQLPIPSWithDiscriminator
      params:
        disc_conditional: False
        disc_in_channels: 3
        disc_start: 10000
        disc_weight: 0.8
        codebook_weight: 1.0

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 6
    num_workers: 6
    train:
      target: taming.data.chroma.ChromaTrain
      params:
        togray: scale_with_invert
        training_images_list_file: datasets/train.txt
        size: 256
    validation:
      target: taming.data.chroma.ChromaTest
      params:
        togray: scale_with_invert
        test_images_list_file: datasets/test.txt
        size: 256
